"""Structured RetinaXplain report normalization and PDF rendering."""

from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape


DISCLAIMER = (
    "This report is generated by RetinaXplain as an AI-assisted screening aid. "
    "It is not a definitive diagnosis and must be reviewed by a qualified "
    "medical professional."
)


def normalize_report(payload: dict) -> dict:
    """Keep report fields predictable while preserving unavailable values."""
    eyes = [eye for eye in (payload.get("eyes") or []) if isinstance(eye, dict)]
    normalized = dict(payload)
    normalized["eyes"] = eyes
    normalized["analysis_datetime"] = payload.get("analysis_datetime") or "Unavailable"
    normalized["report_id"] = payload.get("report_id") or "Unavailable"
    normalized["doctor_llm_recommendation"] = payload.get("doctor_llm_recommendation")
    normalized["doctor_pathologist_comment"] = payload.get("doctor_pathologist_comment") or ""
    normalized["disclaimer"] = payload.get("disclaimer") or DISCLAIMER
    return normalized


def _image_path(root_dir: Path, url: str | None) -> Path | None:
    if not url or not isinstance(url, str) or not url.startswith("/outputs/"):
        return None
    relative_url = url.removeprefix("/outputs/")
    candidate = (root_dir / "runtime" / "outputs" / relative_url).resolve()
    try:
        candidate.relative_to((root_dir / "runtime" / "outputs").resolve())
    except ValueError:
        return None
    return candidate if candidate.is_file() else None


def render_pdf(report: dict, output_path: Path, root_dir: Path) -> None:
    """Render a professional, dynamic medical AI screening report."""
    from reportlab.graphics.shapes import Drawing, Rect
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Flowable,
        Image,
        PageBreak,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    navy = colors.HexColor("#102a43")
    blue = colors.HexColor("#2f6f9f")
    purple = colors.HexColor("#6f42c1")
    orange = colors.HexColor("#c86b22")
    gray = colors.HexColor("#586776")

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="ReportTitle", parent=styles["Title"], textColor=navy, fontSize=18, leading=22, alignment=TA_LEFT))
    styles.add(ParagraphStyle(name="ReportSubtitle", parent=styles["Normal"], textColor=gray, fontSize=8.5, leading=11))
    styles.add(ParagraphStyle(name="Section", parent=styles["Heading2"], textColor=navy, fontSize=11, leading=14, spaceBefore=7, spaceAfter=4))
    styles.add(ParagraphStyle(name="SubSection", parent=styles["Normal"], textColor=navy, fontSize=9.5, leading=12, fontName="Helvetica-Bold", spaceBefore=4, spaceAfter=2))
    styles.add(ParagraphStyle(name="Small", parent=styles["BodyText"], textColor=gray, fontSize=8, leading=10.5))
    styles.add(ParagraphStyle(name="SmallBold", parent=styles["Small"], fontName="Helvetica-Bold", textColor=navy))
    styles.add(ParagraphStyle(name="Right", parent=styles["Small"], alignment=TA_RIGHT))
    styles.add(ParagraphStyle(name="Center", parent=styles["Small"], alignment=TA_CENTER))
    styles.add(ParagraphStyle(name="CardHeader", parent=styles["Normal"], textColor=navy, fontSize=8, leading=10, fontName="Helvetica-Bold", alignment=TA_CENTER))
    styles.add(ParagraphStyle(name="UnavailableText", parent=styles["Normal"], textColor=colors.HexColor("#94a3b8"), fontSize=8, leading=10, alignment=TA_CENTER))
    styles.add(ParagraphStyle(name="RecommendationText", parent=styles["Normal"], textColor=colors.HexColor("#1e293b"), fontSize=8.5, leading=12))
    styles.add(ParagraphStyle(name="WarningIcon", parent=styles["Normal"], textColor=colors.HexColor("#b42318"), fontSize=13, leading=14, fontName="Helvetica-Bold", alignment=TA_CENTER))

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
    )
    story: list = []

    # Page 1 Header
    story.append(Paragraph("RetinaXplain", styles["ReportTitle"]))
    story.append(Paragraph("Explainable AI-Assisted Diabetic Retinopathy Screening", styles["ReportSubtitle"]))
    story.append(Spacer(1, 3 * mm))

    # Evaluation Performance Banner
    perf_table = Table(
        [[
            Paragraph("<b>Evaluation Performance on Project Dataset</b>", styles["SmallBold"]),
            Paragraph("Sensitivity: <b>95.29%</b> | Specificity: <b>99.14%</b> | AUC: <b>0.997</b>", styles["Right"]),
        ]],
        colWidths=[75 * mm, 105 * mm],
        style=TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#edf5fb")),
            ("BOX", (0, 0), (-1, -1), 0.5, blue),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]),
    )
    story.append(perf_table)
    story.append(Spacer(1, 2.5 * mm))

    # Report Information
    story.append(Paragraph("Report Information", styles["Section"]))
    info_table = Table(
        [
            ["Date and Time of Analysis", str(report.get("analysis_datetime", "Unavailable"))],
            ["Eye Analyzed", str(report.get("eye_analyzed", "Unavailable"))],
            ["Report Type", str(report.get("report_type", "AI-assisted screening"))],
        ],
        colWidths=[55 * mm, 125 * mm],
        style=TableStyle([
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d8e0e8")),
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f4f7fa")),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("TEXTCOLOR", (0, 0), (0, -1), navy),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 2.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ]),
    )
    story.append(info_table)
    story.append(Spacer(1, 2.5 * mm))

    # Screening Summary
    story.append(Paragraph("Screening Summary", styles["Section"]))
    summary_rows = [["Eye", "Predicted DR Grade", "Screening Category", "Model Confidence"]]
    eyes = report.get("eyes", [])
    if eyes:
        for eye in eyes:
            grade = eye.get("predicted_grade")
            grade_str = f"Grade {grade}" if grade is not None else "Unavailable"
            category = str(eye.get("screening_category") or "Unavailable")
            conf = eye.get("model_confidence")
            conf_str = f"{float(conf) * 100:.2f}% (uncalibrated)" if conf is not None else "Unavailable"
            summary_rows.append([
                str(eye.get("eye_name", "Eye")),
                grade_str,
                category,
                conf_str,
            ])
    else:
        summary_rows.append(["Unavailable", "Unavailable", "Unavailable", "Unavailable"])

    summary_table = Table(
        summary_rows,
        colWidths=[42 * mm, 42 * mm, 46 * mm, 50 * mm],
        style=TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#edf5fb")),
            ("TEXTCOLOR", (0, 0), (-1, 0), navy),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 8),
            ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f8fafc")),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("TEXTCOLOR", (0, 1), (-1, -1), navy),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#bcccdc")),
            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#d8e0e8")),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]),
    )
    story.append(summary_table)
    story.append(Spacer(1, 2.5 * mm))

    # Helper for horizontal graphical lesion bar
    def _create_lesion_bar(count: int, max_val: int, bar_w: float = 100 * mm, bar_h: float = 4.5 * mm) -> Drawing:
        d = Drawing(bar_w, bar_h)
        # Background track
        d.add(Rect(0, 0.5 * mm, bar_w, bar_h - 1 * mm, fillColor=colors.HexColor("#f1f5f9"), strokeColor=None, rx=2, ry=2))
        # Foreground fill
        if max_val > 0 and count > 0:
            fill_w = max(3.0, (count / max_val) * bar_w)
            d.add(Rect(0, 0.5 * mm, fill_w, bar_h - 1 * mm, fillColor=orange, strokeColor=None, rx=2, ry=2))
        return d

    # Helper for 3-column image card
    def _create_image_card(label: str, img_path: Path | None) -> Table:
        if img_path:
            content = Image(str(img_path), width=54 * mm, height=38 * mm, kind="proportional")
        else:
            content = Paragraph('<font color="#8898aa">Image unavailable</font>', styles["UnavailableText"])
        return Table(
            [
                [Paragraph(f"<b>{label}</b>", styles["CardHeader"])],
                [content],
            ],
            colWidths=[58 * mm],
            rowHeights=[9 * mm, 40 * mm],
            style=TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#edf2f7")),
                ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f8fafc")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.HexColor("#cbd5e1")),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
                ("LEFTPADDING", (0, 0), (-1, -1), 2),
                ("RIGHTPADDING", (0, 0), (-1, -1), 2),
            ]),
        )

    for index, eye in enumerate(eyes):
        eye_name = eye.get("eye_name", "Eye")
        story.append(Paragraph(f"{eye_name} Analysis", styles["Section"]))
        story.append(Paragraph(f"<b>Image Source:</b> {eye.get('image_source', 'Unavailable')}", styles["Small"]))
        story.append(Spacer(1, 2 * mm))

        # 3-column horizontal card grid
        fundus_p = _image_path(root_dir, eye.get("image_path"))
        gradcam_p = _image_path(root_dir, eye.get("gradcam_path") or eye.get("grad_cam_path"))
        lesion_p = _image_path(root_dir, eye.get("annotated_image_path") or eye.get("annotated_path"))

        card_fundus = _create_image_card("Original Fundus Image", fundus_p)
        card_gradcam = _create_image_card("Grad-CAM Prediction-Relevant Regions", gradcam_p)
        card_lesion = _create_image_card("Lesion-Based Annotations", lesion_p)

        grid_table = Table(
            [[card_fundus, card_gradcam, card_lesion]],
            colWidths=[58 * mm, 58 * mm, 58 * mm],
            style=TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 1),
                ("RIGHTPADDING", (0, 0), (-1, -1), 1),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]),
        )
        story.append(grid_table)
        story.append(Spacer(1, 1.5 * mm))
        story.append(Paragraph(
            "<i>Grad-CAM highlights prediction-relevant regions, while lesion annotations show retinal lesion evidence detected by Module 2.</i>",
            styles["Small"],
        ))
        story.append(Spacer(1, 3 * mm))

        # DR Severity Probabilities Table
        story.append(Paragraph("DR Severity Probabilities", styles["SubSection"]))
        probs = eye.get("grade_probabilities") or []
        pred_grade = eye.get("predicted_grade")
        prob_rows = [["DR Severity Grade", "Probability"]]
        prob_style = [
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3edf9")),
            ("TEXTCOLOR", (0, 0), (-1, 0), purple),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e8edf2")),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]

        if probs:
            for i, val in enumerate(probs[:5]):
                is_predicted = (pred_grade is not None and str(pred_grade) == str(i))
                p_text = f"{float(val) * 100:.2f}%"
                row_idx = len(prob_rows)
                if is_predicted:
                    prob_rows.append([f"Grade {i} [Predicted]", p_text])
                    prob_style.extend([
                        ("BACKGROUND", (0, row_idx), (-1, row_idx), colors.HexColor("#f5f0fa")),
                        ("TEXTCOLOR", (0, row_idx), (-1, row_idx), purple),
                        ("FONTNAME", (0, row_idx), (-1, row_idx), "Helvetica-Bold"),
                    ])
                else:
                    prob_rows.append([f"Grade {i}", p_text])
        else:
            prob_rows.append(["Probability data unavailable", "—"])

        prob_table = Table(prob_rows, colWidths=[90 * mm, 90 * mm], style=TableStyle(prob_style))
        story.append(prob_table)
        story.append(Spacer(1, 3 * mm))

        # Detected Retinal Lesions Section (Graphical Rectangular Bars)
        story.append(Paragraph("Detected Retinal Lesions", styles["SubSection"]))
        lesion_counts = eye.get("lesion_counts") or {}
        lesion_rows = [["Lesion Type", "Relative Severity / Proportion", "Count"]]
        if lesion_counts:
            max_c = max([int(v or 0) for v in lesion_counts.values()] + [1])
            for l_name, l_val in lesion_counts.items():
                c_int = max(0, int(l_val or 0))
                bar_draw = _create_lesion_bar(c_int, max_c, bar_w=105 * mm, bar_h=4.5 * mm)
                lesion_rows.append([str(l_name), bar_draw, str(c_int)])
        else:
            lesion_rows.append(["No lesions detected", "—", "0"])

        lesion_table = Table(
            lesion_rows,
            colWidths=[45 * mm, 110 * mm, 25 * mm],
            style=TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#fff4e9")),
                ("TEXTCOLOR", (0, 0), (-1, 0), orange),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e7d8cb")),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ALIGN", (2, 0), (2, -1), "CENTER"),
                ("TOPPADDING", (0, 0), (-1, -1), 2.5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
            ]),
        )
        story.append(lesion_table)
        story.append(Spacer(1, 4 * mm))

        if index < len(eyes) - 1:
            story.append(PageBreak())

    # Break to Page 2 for Clinical Recommendations & Review
    if eyes:
        story.append(PageBreak())

    # Page 2: Clinical Recommendations & Review
    story.append(Paragraph("RetinaXplain — Clinical Findings & Recommendations", styles["ReportTitle"]))
    story.append(Paragraph(
        f"Report ID: <b>{report.get('report_id', 'Unavailable')}</b> | "
        f"Date: <b>{report.get('analysis_datetime', 'Unavailable')}</b> | "
        f"Eye Analyzed: <b>{report.get('eye_analyzed', 'Unavailable')}</b>",
        styles["ReportSubtitle"],
    ))
    story.append(Spacer(1, 4 * mm))

    # AI Screening Recommendation
    story.append(Paragraph("AI Screening Recommendation", styles["Section"]))
    referable_eyes = [
        str(eye.get("eye_name", "Eye"))
        for eye in eyes
        if str(eye.get("screening_category", "")).lower().startswith("referable")
    ]
    if referable_eyes:
        if len(referable_eyes) == 2:
            affected_eyes = "both eyes"
            eye_phrase = "in both eyes"
        else:
            affected_eyes = referable_eyes[0].lower()
            eye_phrase = f"in the {escape(affected_eyes)}"
        ai_rec_text = (
            "<b>Further ophthalmological evaluation is recommended.</b> "
            f"The screening findings indicate referable diabetic retinopathy {eye_phrase}."
        )
    else:
        ai_recs = []
        for eye in eyes:
            rec = eye.get("ai_recommendation")
            if rec:
                ai_recs.append(f"<b>{escape(str(eye.get('eye_name', 'Eye')))}:</b> {escape(str(rec))}" if len(eyes) > 1 else escape(str(rec)))
        if not ai_recs and report.get("ai_recommendation"):
            ai_recs.append(escape(str(report["ai_recommendation"])))
        ai_rec_text = "<br/><br/>".join(ai_recs) if ai_recs else "No AI screening recommendation was generated."

    ai_rec_table = Table(
        [[Paragraph(ai_rec_text, styles["RecommendationText"])]],
        colWidths=[180 * mm],
        style=TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f0f6fc")),
            ("BOX", (0, 0), (-1, -1), 0.5, blue),
            ("LINELEFT", (0, 0), (-1, -1), 2.5, blue),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("LEFTPADDING", (0, 0), (-1, -1), 9),
            ("RIGHTPADDING", (0, 0), (-1, -1), 9),
        ]),
    )
    story.append(ai_rec_table)
    story.append(Spacer(1, 4 * mm))

    # Clinician comment (if available)
    if report.get("doctor_pathologist_comment"):
        story.append(Paragraph("Clinician Comment", styles["Section"]))
        doc_comment_table = Table(
            [[Paragraph(escape(str(report["doctor_pathologist_comment"])), styles["RecommendationText"])]],
            colWidths=[180 * mm],
            style=TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fffdfa")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ("LINELEFT", (0, 0), (-1, -1), 2.5, orange),
                ("TOPPADDING", (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
                ("LEFTPADDING", (0, 0), (-1, -1), 9),
                ("RIGHTPADDING", (0, 0), (-1, -1), 9),
            ]),
        )
        story.append(doc_comment_table)
        story.append(Spacer(1, 6 * mm))
    else:
        story.append(Spacer(1, 4 * mm))

    # Clinical Disclaimer Box
    disc_table = Table(
        [[
            Paragraph("!", styles["WarningIcon"]),
            Paragraph(f"<b>CLINICAL DISCLAIMER:</b> {escape(str(report.get('disclaimer', DISCLAIMER)))}", styles["Small"]),
        ]],
        colWidths=[10 * mm, 170 * mm],
        style=TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fff0f0")),
            ("BOX", (0, 0), (-1, -1), 0.7, colors.HexColor("#f3a6a0")),
            ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#ffe0de")),
            ("LINEAFTER", (0, 0), (0, 0), 0.5, colors.HexColor("#f3a6a0")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]),
    )
    story.append(disc_table)

    doc.build(story)
